### ISSUE TITLE
Missing min-hx and min-wx

### ISSUE THREAD

**Issue by MartinKavik** [lamhieu-vk/ciser#3]
@lamhieu-vk Hi!
Could I send PR for some more **.min-xy**? E.g.:

```
.min-h1 { min-height: 1rem; }
.min-h1s { min-height: 1.5rem; }
     ...
```

```
.min-w1 { min-width: 1rem; }
.min-w1s { min-width: 1.5rem; }
     ...
```

**Comment by lh0x00** [comment]
Hi @MartinKavik , After you have researched and analyzed, I found that value is not used much in the general case of many websites.
Because if you just create a certain value range, it will not help you.
Current ciser supports min-max values according to 25, 50, 75, 100 by percent or percent of screen parameters, you can see more [here](https://github.com/lamhieu-vk/ciser/blob/master/docs/heights.md).
Thanks for issue 👍
